name: simple-semaphore CI (Lint & Test)

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: kkrypt0nn/actions/.github/workflows/rust_ci.yaml@f87e74587c75a99d661e5966fc41552d106a3712 # v0.1.1
